version: '1'
services:
  java_crud:
    image: java_crud:1.0
    environment:
      - MONGODB_CONNSTRING=mongodb://shreyas:shreyas123@mongodb
    ports:
      - 8080:8080
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shreyas
      - MONGO-INITDB_ROOT_PASSWORD=shreyas123
  postgres:
    image: postgres:13.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

